import { IProduct } from "@/types";


export const ListProducts: IProduct[] = [
   { id: 1, name: "Andes Premium Coffee", price: 1499.99, description: "High-altitude coffee with rich flavor.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 45 },
  { id: 2, name: "Valley Smooth Coffee", price: 1250.50, description: "Soft aroma with fruity notes.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 67 },
  { id: 3, name: "Intense Espresso Roast", price: 1599.99, description: "Strong roast with full body.", image: "/assets/bolsaCafe (3).png", categoryId: 1, stock: 39 },
  { id: 4, name: "Organic Sierra Coffee", price: 1625.75, description: "Organic beans, smooth balance.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 82 },
  { id: 5, name: "Natural Decaf Coffee", price: 1340.00, description: "Full flavor, caffeine-free.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 54 },
  { id: 6, name: "House Blend Coffee", price: 1199.99, description: "Classic everyday blend.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 70 },
  { id: 7, name: "Special Reserve Coffee", price: 1850.50, description: "Single-origin selected beans.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 28 },
  { id: 8, name: "Mountain Gourmet Coffee", price: 1799.99, description: "Medium roast, sweet notes.", image: "/assets/bolsaCafe (3).png", categoryId: 1, stock: 91 },
  { id: 9, name: "Fine Ground Coffee", price: 1299.99, description: "Perfect for espresso lovers.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 32 },
  { id: 10, name: "Coarse Ground Coffee", price: 1299.99, description: "Ideal for French press brewing.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 88 },
  { id: 11, name: "Caramel Blend Coffee", price: 1450.75, description: "Sweet and creamy aroma.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 63 },
  { id: 12, name: "Dark Chocolate Roast", price: 1475.25, description: "Deep roast with cocoa tones.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 77 },
  { id: 13, name: "Floral Aroma Coffee", price: 1380.60, description: "Light acidity and floral scent.", image: "/assets/bolsaCafe (3).png", categoryId: 1, stock: 49 },
  { id: 14, name: "Toasted Nut Coffee", price: 1520.30, description: "Warm, nutty flavor.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 21 },
  { id: 15, name: "Honey Forest Coffee", price: 1610.40, description: "Sweet honey and nut notes.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 74 },
  { id: 16, name: "Black Premium Bag", price: 999.99, description: "Durable bag for storing beans.", image: "/assets/blackBag.png", categoryId: 2, stock: 57 },
  { id: 17, name: "Pink Limited Bag", price: 1050.99, description: "Modern and elegant design.", image: "/assets/pinkBag.png", categoryId: 2, stock: 65 },
  { id: 18, name: "Reusable Coffee Bag", price: 890.50, description: "Keeps aroma fresh longer.", image: "/assets/bolsaCafe (3).png", categoryId: 2, stock: 42 },
  { id: 19, name: "Traditional Field Coffee", price: 1199.99, description: "Classic handmade taste.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 86 },
  { id: 20, name: "Sweet Natural Coffee", price: 1325.00, description: "Soft and naturally sweet.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 59 },
  { id: 21, name: "Dark Strong Coffee", price: 1599.99, description: "Bold and powerful roast.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 34 },
  { id: 22, name: "Morning Light Coffee", price: 1175.25, description: "Perfect way to start the day.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 79 },
  { id: 23, name: "Signature Farm Coffee", price: 1999.99, description: "Exclusive farm-grown beans.", image: "/assets/bolsaCafe (3).png", categoryId: 1, stock: 25 },
  { id: 24, name: "Serrano Bold Roast", price: 1650.30, description: "Rich body and deep flavor.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 92 },
  { id: 25, name: "Mild Sunrise Coffee", price: 1240.00, description: "Balanced and easy to drink.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 48 },
  { id: 26, name: "Golden Roast Coffee", price: 1725.75, description: "Special edition golden pack.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 76 },
  { id: 27, name: "Old Farm Classic", price: 1399.50, description: "Traditional family recipe.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 61 },
  { id: 28, name: "Tropical Blend Coffee", price: 1430.10, description: "Citrus and exotic tones.", image: "/assets/bolsaCafe (3).png", categoryId: 1, stock: 51 },
  { id: 29, name: "Southern Reserve Coffee", price: 1820.20, description: "Medium roast, floral finish.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 84 },
  { id: 30, name: "Classic Moka Coffee", price: 1375.35, description: "Perfect balance of flavor.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 47 },
  { id: 31, name: "Colombian Origin Coffee", price: 1790.99, description: "Sweet finish, strong aroma.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 72 },
  { id: 32, name: "Italian Espresso Roast", price: 1680.75, description: "European style espresso roast.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 44 },
  { id: 33, name: "Summer Special Coffee", price: 1410.60, description: "Perfect for iced or cold brew.", image: "/assets/bolsaCafe (3).png", categoryId: 1, stock: 67 },
  { id: 34, name: "Dulce de Leche Coffee", price: 1550.20, description: "Creamy caramel touch.", image: "/assets/bolsaCafe (2).png", categoryId: 1, stock: 31 },
  { id: 35, name: "Cinnamon Blend Coffee", price: 1499.99, description: "Warm and aromatic taste.", image: "/assets/bolsaCafe (4).png", categoryId: 1, stock: 66 },
  { id: 36, name: "Forest Intense Roast", price: 1760.25, description: "Cocoa and wood aroma.", image: "/assets/bolsaCafe (5).png", categoryId: 1, stock: 53 },
  { id: 37, name: "Golden Honey Coffee", price: 1620.40, description: "Naturally sweet and smooth.", image: "/assets/bolsaCafe (1).png", categoryId: 1, stock: 81 },
  { id: 38, name: "Black Classic Bag", price: 899.99, description: "Ideal for coffee packaging.", image: "/assets/blackBag.png", categoryId: 2, stock: 90 },
  { id: 39, name: "Pink Coffee Lovers Bag", price: 949.50, description: "Stylish and modern look.", image: "/assets/pinkBag.png", categoryId: 2, stock: 36 },
  { id: 40, name: "Reinforced Premium Bag", price: 1099.99, description: "Durable and reusable bag.", image: "/assets/blackBag.png", categoryId: 2, stock: 58 },
];